// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextTurn.Infrastructure.Persistence;

#nullable disable

namespace NextTurn.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326044222_AddStaffManagement")]
    partial class AddStaffManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NextTurn.Domain.Appointment.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LateCancellation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SlotEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SlotStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Confirmed");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "AppointmentProfileId", "SlotStart")
                        .HasDatabaseName("IX_Appointments_OrganisationId_ProfileId_SlotStart");

                    b.HasIndex("OrganisationId", "AppointmentProfileId", "SlotStart", "SlotEnd")
                        .IsUnique()
                        .HasDatabaseName("UX_Appointments_OrganisationId_ProfileId_SlotStart_SlotEnd_Active")
                        .HasFilter("[Status] <> 'Cancelled' AND [Status] <> 'Rescheduled'");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Appointment.Entities.AppointmentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShareableLink")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("IX_AppointmentProfiles_OrganisationId");

                    b.HasIndex("OrganisationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_AppointmentProfiles_OrganisationId_Name");

                    b.ToTable("AppointmentProfiles", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Appointment.Entities.AppointmentScheduleRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "AppointmentProfileId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("UX_AppointmentScheduleRules_OrganisationId_ProfileId_DayOfWeek");

                    b.ToTable("AppointmentScheduleRules", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Auth.Entities.StaffOfficeAssignment", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OrganisationId", "StaffUserId", "OfficeId");

                    b.HasIndex("OrganisationId", "OfficeId");

                    b.HasIndex("OrganisationId", "StaffUserId")
                        .HasDatabaseName("IX_StaffOfficeAssignments_Org_Staff");

                    b.ToTable("StaffOfficeAssignments", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CounterName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.Property<TimeSpan?>("ShiftEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ShiftStart")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset?>("StaffInviteExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StaffInviteTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("StaffInviteTokenHash")
                        .HasDatabaseName("IX_Users_StaffInviteTokenHash");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Office.Entities.Office", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "IsActive")
                        .HasDatabaseName("IX_Offices_OrganisationId_IsActive");

                    b.HasIndex("OrganisationId", "Name")
                        .HasDatabaseName("IX_Offices_OrganisationId_Name");

                    b.ToTable("Offices", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Organisation.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PendingApproval");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Organisations_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Organisations_Slug");

                    b.ToTable("Organisations", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Queue.Entities.Queue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AverageServiceTimeSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("IX_Queues_OrganisationId");

                    b.ToTable("Queues", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Queue.Entities.QueueActionAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QueueEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("QueueEntryId");

                    b.HasIndex("QueueId", "CreatedAt")
                        .HasDatabaseName("IX_QueueActionAuditLogs_QueueId_CreatedAt");

                    b.ToTable("QueueActionAuditLogs", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Queue.Entities.QueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Waiting");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QueueId")
                        .IsUnique()
                        .HasDatabaseName("UX_QueueEntries_QueueId_OneServing")
                        .HasFilter("[Status] = 'Serving'");

                    b.HasIndex("QueueId", "Status")
                        .HasDatabaseName("IX_QueueEntries_QueueId_Status");

                    b.HasIndex("QueueId", "UserId")
                        .HasDatabaseName("IX_QueueEntries_QueueId_UserId");

                    b.ToTable("QueueEntries", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Queue.Entities.QueueStaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("IX_QueueStaffAssignments_OrganisationId");

                    b.HasIndex("QueueId", "StaffUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_QueueStaffAssignments_QueueId_StaffUserId");

                    b.ToTable("QueueStaffAssignments", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Service.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "Code")
                        .IsUnique();

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Service.Entities.ServiceOfficeAssignment", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OrganisationId", "ServiceId", "OfficeId");

                    b.HasIndex("OrganisationId", "OfficeId");

                    b.ToTable("ServiceOfficeAssignments", (string)null);
                });

            modelBuilder.Entity("NextTurn.Domain.Auth.Entities.StaffOfficeAssignment", b =>
                {
                    b.HasOne("NextTurn.Domain.Office.Entities.Office", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId", "OfficeId")
                        .HasPrincipalKey("OrganisationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextTurn.Domain.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId", "StaffUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NextTurn.Domain.Auth.Entities.User", b =>
                {
                    b.OwnsOne("NextTurn.Domain.Auth.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("TenantId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("TenantId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("TenantId", "Value")
                                .IsUnique()
                                .HasDatabaseName("IX_Users_TenantId_Email");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("NextTurn.Domain.Organisation.Entities.Organisation", b =>
                {
                    b.OwnsOne("NextTurn.Domain.Auth.ValueObjects.EmailAddress", "AdminEmail", b1 =>
                        {
                            b1.Property<Guid>("OrganisationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("AdminEmail");

                            b1.HasKey("OrganisationId");

                            b1.ToTable("Organisations");

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId");
                        });

                    b.OwnsOne("NextTurn.Domain.Organisation.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrganisationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("AddressLine1");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("AddressPostalCode");

                            b1.HasKey("OrganisationId");

                            b1.ToTable("Organisations");

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("AdminEmail")
                        .IsRequired();
                });

            modelBuilder.Entity("NextTurn.Domain.Queue.Entities.QueueActionAuditLog", b =>
                {
                    b.HasOne("NextTurn.Domain.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextTurn.Domain.Queue.Entities.QueueEntry", null)
                        .WithMany()
                        .HasForeignKey("QueueEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextTurn.Domain.Queue.Entities.Queue", null)
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NextTurn.Domain.Queue.Entities.QueueEntry", b =>
                {
                    b.HasOne("NextTurn.Domain.Queue.Entities.Queue", null)
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NextTurn.Domain.Service.Entities.ServiceOfficeAssignment", b =>
                {
                    b.HasOne("NextTurn.Domain.Office.Entities.Office", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId", "OfficeId")
                        .HasPrincipalKey("OrganisationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NextTurn.Domain.Service.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId", "ServiceId")
                        .HasPrincipalKey("OrganisationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
